### ISSUE TITLE
As citizen I want to specify a certain type of request so that my request can be fulfilled

### ISSUE THREAD

**Issue by ilagioda** [ilagioda/SoftEng2#1]
As **citizen**
I want to **specify a certain type of request**
so that **my request can be fulfilled**

**Comment by ilagioda** [comment]
- [ ] prova1

- [ ] prova2
- [ ] prova3

**Comment by MCipriano0** [comment]
- [ ] prova1
- [ ] prova2
- [ ] prova3

**Comment by ilagioda** [comment]
- [ ] environment settings (6 * 1h) 
- [ ] definition and creation of Model classes and functions (2 * 1h)  @MCipriano0 / @F-Walter 
- [ ] definition and creation of GUI (0.5h)  @simo-gen 
- [ ] creation of controller class (1h)  @GianlucaBrezzo 
- [ ] unit tests (1h)  @96sparrow 
- [ ] system testing (E2E) (0.5h)  @ilagioda 
- [ ] code review (6 * 0.5h)  @all

TOTAL HOURS: 14h
